name: Slack
on:
  pull_request:
    types: [opened]
  
jobs:
   slack:
    name: Slack alert
    if: ${{ github.head_ref != 'bot/**' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{
  \"channel\":\"C020ZE4491U\", 
	\"attachments\": [
		{
			\"color\": \"#E4D00A\",
			\"blocks\": [
				{
					\"type\": \"header\",
					\"text\": {
						\"type\": \"plain_text\",
						\"text\": \"New Pull Request Awaiting Review\",
						\"emoji\": true
					}
				},
				{
					\"type\": \"section\",
					\"fields\": [
						{
							\"type\": \"mrkdwn\",
							\"text\": \":technologist:*User*\n<@${{github.event.pull_request.user.login}}> :60fps_parrot:\"
						},
						{
							\"type\": \"mrkdwn\",
							\"text\": \":github: *Repository*\n<${{github.event.repository.html_url}}|${{github.repository}}>\"
						}
					]
				},
				{
					\"type\": \"section\",
					\"fields\": [
						{
							\"type\": \"mrkdwn\",
							\"text\": \":earth_africa: *PR URL*\n${{github.event.pull_request.html_url}}\"
						},
						{
							\"type\": \"mrkdwn\",
							\"text\": \":books: *PR Title*\n${{github.event.pull_request.title}}\"
						}
					]
				},
				{
					\"type\": \"section\",
					\"text\": {
						\"type\": \"mrkdwn\",
						\"text\": \"Your reviews are appreciated.\"
					},
					\"accessory\": {
						\"type\": \"button\",
						\"text\": {
							\"type\": \"plain_text\",
							\"text\": \"View Pull Request :github:\",
							\"emoji\": true
						},
						\"value\": \"click_me_123\",
						\"url\": \"${{github.event.pull_request.html_url}}\",
						\"action_id\": \"button-action\"
					}
				}
			]
		}
	]
}'